### ISSUE TITLE
JobForm: Make "Description" Field a Multi-Line Field

### ISSUE THREAD

**Issue by cofonseca** [xracer6/BayDay#28]
The "Description" field on the "Add a Job" form should be a multi-line [textarea](https://www.w3schools.com/tags/tag_textarea.asp), which will encourage people to add longer and more detailed descriptions of the work that needs to be done.

**Comment by xracer6** [comment]
The "Description" column was changed to having a "textarea" type field. Also refined the margin for the form at the bottom of the page for a cleaner look. Tested to confirm function and make sure database communication when submitting was not effected.
